#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : itsdangerous
Version  : 0.24
Release  : 24
URL      : https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz
Source0  : https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz
Summary  : Various helpers to pass trusted data to untrusted environments and back.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: itsdangerous-python3
Requires: itsdangerous-license
Requires: itsdangerous-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
It's Dangerous
... so better sign this
Various helpers to pass data to untrusted environments and to get it back
safe and sound.

%package license
Summary: license components for the itsdangerous package.
Group: Default

%description license
license components for the itsdangerous package.


%package python
Summary: python components for the itsdangerous package.
Group: Default
Requires: itsdangerous-python3

%description python
python components for the itsdangerous package.


%package python3
Summary: python3 components for the itsdangerous package.
Group: Default
Requires: python3-core

%description python3
python3 components for the itsdangerous package.


%prep
%setup -q -n itsdangerous-0.24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532377013
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python tests.py
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/itsdangerous
cp LICENSE %{buildroot}/usr/share/doc/itsdangerous/LICENSE
cp docs/_themes/LICENSE %{buildroot}/usr/share/doc/itsdangerous/docs__themes_LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/itsdangerous/LICENSE
/usr/share/doc/itsdangerous/docs__themes_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
